export const LOAD_PORTFOLIO_LOADING = "LOAD_PORTFOLIO_LOADING";
export const LOAD_PORTFOLIO_SUCCESS = "LOAD_PORTFOLIO_SUCCESS";
export const LOAD_PORTFOLIO_ERROR = "LOAD_PORTFOLIO_ERROR";

export const LOAD_USER_LOADING = "LOAD_USER_LOADING";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_ERROR = "LOAD_USER_ERROR";
export const USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN ";

export const LOAD_COINS_LOADING = "LOAD_COINS_LOADING";
export const LOAD_COINS_SUCCESS = "LOAD_COINS_SUCCESS";
export const LOAD_COINS_ERROR = "LOAD_COINS_ERROR";
